### ISSUE TITLE
normalized_query_hash tip

### ISSUE THREAD

**Issue by alrocar** [tinybirdco/clickhouse_knowledge_base#13]
Leaving an issue open for now, will create a PR with more details.

When looking for distinct queries in the `query_log` @Algunenano suggested to discard similar ones (for instance same where filter with different values), you can deduplicate those with the same `normalized_query_hash`.

**Comment by Algunenano** [comment]
Related:
- https://gitlab.com/tinybird/clickhouse-kb-doc-a-thon/-/merge_requests/4
- https://gitlab.com/tinybird/clickhouse-kb-doc-a-thon/-/merge_requests/107

No idea how the 2 projects are merged together

**Comment by alrocar** [comment]
Oh OK! so we already have a tip for that 😅 

> No idea how the 2 projects are merged together

@sdairs I understand all new stuff should go under this GitHub repo?

**Comment by sdairs** [comment]
@alrocar correct, you can submit new tips directly as a PR to this repo :) I am still working through the backlog of tips submitted previously
