### ISSUE TITLE
typo: change 'alot' to 'a lot'

### ISSUE THREAD

**Issue by AlisonDavey** [tinybirdco/clickhouse_knowledge_base#9]
[clickhouse_knowledge_base](https://github.com/tinybirdco/clickhouse_knowledge_base)/[knowledge-base](https://github.com/tinybirdco/clickhouse_knowledge_base/tree/main/knowledge-base)/[docs](https://github.com/tinybirdco/clickhouse_knowledge_base/tree/main/knowledge-base/docs)/intro.md

Change from

Tinybird uses ClickHouse under the hood, we've learned alot about it over the years, and we wanted to start sharing our knowledge with the ClickHouse community.

to

Tinybird uses ClickHouse under the hood, we've learned a lot about it over the years, and we wanted to start sharing our knowledge with the ClickHouse community.

**Comment by sdairs** [comment]
Thanks @AlisonDavey - fixed in https://github.com/tinybirdco/clickhouse_knowledge_base/commit/21d88394745997157cea527ea478bb408b9216df
